source_data:
  folder_path: ../../data
  num_files: 2

minio:
  endpoint: localhost:9000
  access_key: minio_access_key
  secret_key: minio_secret_key

datalake:
  bronze:
    bucket_name: bronze
    folder_name: raw
    description: "Raw data storage layer"
    retention_days: 90
    enabled: true

  silver:
    bucket_name: silver
    folder_name: processed
    description: "Processed and cleaned data layer"
    retention_days: 60
    enabled: true

processing:
  batch_size: 1000
  parallel_jobs: 4
  error_handling:
    max_retries: 3
    retry_delay_seconds: 60